# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tecnología en Criollo
subtitle: Version 0.0.2
name: Jere Baez Carballo
email:
description: >- # this means to ignore newlines until "baseurl:"
  "Una página sobre ingeniería, programación, y tecnología en general escrito en idioma argento con acento cordobés.
  Proyectos de fin de semana, artículos, tutoriales, cursos y algo más."
github_username: jeremiasbaezcarballo
minimal_mistakes_skin: dark
url: "https://tecnologiaencriollo.com"
baseurl: ""
locale: "es-ES"
search: true
teaser: /assets/images/site/tec-default-teaser-500x300.png
logo: /assets/images/site/tec-logo-88x88.png
masthead_tittle: "Tecnología... en criollo!"
show_date: true
show_author: true
read_time: true
words_per_minute: 250

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/Argentina/Cordoba"
include:
  - _pages
  - _courses

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XVXW1XJSE8"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-spaceship
  - jekyll-polyglot

languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false
whitelist:
  - jekyll-redirect-from

github: [metadata]

author:
  name: "Jere Baez Carballo"
  avatar: https://avatars.githubusercontent.com/u/105991550?v=4
  bio: ""
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeremiasbaezcarballo"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: False
  - scope:
      path: "_courses"
      type: courses
    values:
      layout: single
      author_profile: False

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
